# This is a basic workflow that is manually triggered

name: Build

on:
  push:
  workflow_dispatch: # This triggers the workflow manually
    inputs:
      version_update_type:
        description: 'update type'
        required: true
        type: choice
        options:
        - rc
        - dev
        - post
        - patch
        - newversion

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
         

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install towncrier twisted incremental

    - name: Upgrade version
      run: |
        python -m incremental.update app --${{ inputs.environment_name }}
    
    - name: Get application Version
      id: appVersion
      run: |
        echo "version=$(python app/_version.py)" >> "$GITHUB_OUTPUT"

    - name: Generate Changelog
      env:
        SELECTED_VERSION: ${{ steps.appVersion.outputs.version }}
      run: towncrier build --yes --version=$SELECTED_VERSION
    
    - name: Commit Changelog
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add CHANGELOG.md
        git commit -m "Update changelog [skip ci]"
        git push origin ${{env.BRANCH_NAME}}

