# This is a basic workflow that is manually triggered

name: Build

on:
  push:
  workflow_dispatch: # This triggers the workflow manually
    inputs:
      version_update_type:
        description: 'update type'
        required: true
        type: choice
        options:
        - rc
        - dev
        - post
        - patch
        - newversion


jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install towncrier incremental

    - name: Upgrade version
      run: |
        python -m incremental.update app --patch
      
    - name: Generate Changelog
      run: towncrier build --yes
    
    - name: Commit Changelog
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add CHANGELOG.md
        git commit -m "Update changelog [skip ci]"
        git push origin main

